
-- Clear existing knowledge base
TRUNCATE TABLE public.knowledge_base;

-- FW1: Value Proposition (10 criteria)
INSERT INTO public.knowledge_base (category, criterion, weight, description) VALUES
('Value Proposition', 'Hero headline answers "what do you do?" in under 5 seconds', 10, 'A stranger with zero context can state back what the company does after reading only the headline. The 5-second test from LIFT: cover everything below the headline. Read it cold. If the answer to "what is this?" requires scrolling or guessing, this fails. The grunt test: could a caveman understand the offer? PASS: "We audit your landing page across 70 criteria and show you exactly what it''s costing you each month." FAIL: "We help ambitious businesses grow." — describes almost any company on earth, zero specificity.'),
('Value Proposition', 'Headline leads with customer outcome, not company mechanism', 10, 'The headline names what the visitor gets or avoids — not what the company does to deliver it. StoryBrand: the customer is the hero, not the brand. PASS: "Stop losing €3,000/month to a landing page that doesn''t convert." FAIL: "We build high-converting landing pages using data-driven CRO methodology." — every sentence starts with "We."'),
('Value Proposition', 'Value proposition is visible above the fold without scrolling', 10, 'The core offer — what, for whom, and why it matters — is readable on page load on both desktop and mobile. The above-fold zone is the only section 100% of visitors see. On mobile, 50–80% of paid traffic visitors never scroll past the first screen. PASS: Headline + sub-headline + CTA button all visible on a 375px mobile viewport. FAIL: Full-screen hero video plays for 8 seconds before text fades in; large decorative hero image pushes headline below fold.'),
('Value Proposition', 'Headline passes the Bly 4 U''s test: Useful, Ultra-specific, Unique, Urgent', 8, 'Score each U independently. The headline must pass at least 3 of 4. Each U adds independent persuasive force. PASS (4/4): "Stop losing €3,200/month to a landing page your visitors can''t navigate in 5 seconds." FAIL (1/4): "We help you grow your business online." — Useful barely, Ultra-specific no, Unique no (every agency says this), Urgent no.'),
('Value Proposition', 'Sub-headline explains the unique mechanism in one sentence', 8, 'The sentence directly below the headline explains how the outcome is delivered, differentiating from alternatives. Google Ads traffic is almost always Schwartz Stage 3 — they know CRO agencies exist, they''re evaluating which one. PASS: "We audit your page across 70 criteria, calculate the monthly revenue you''re losing on each issue, and walk you through the findings — free." FAIL: "We''re a team of experienced conversion specialists dedicated to improving your results." — no mechanism, self-awards.'),
('Value Proposition', 'The offer is differentiated from obvious alternatives', 8, 'A visitor who has seen 2–3 competitors can immediately identify what makes this offer different. The logo swap test: remove the company logo and replace it with a competitor''s. Does the page still make perfect sense? If yes, differentiation has failed. PASS: "Unlike agencies that redesign first and measure later — we calculate the revenue cost of every issue before touching a single pixel." FAIL: "We''re a full-service CRO agency with 10+ years of experience and a client-first approach."'),
('Value Proposition', 'No vague superlatives in headline or opening copy', 8, 'Words like "world-class", "leading", "powerful", "best", "revolutionary", "innovative" are absent from the headline and first paragraph. Ogilvy: "cleans 73% more effectively" is credible because the number implies testing. "Cleans better" is not. PASS: "We audit 70 criteria across 7 CRO frameworks — most agencies check fewer than 20." FAIL: "We deliver world-class, industry-leading conversion optimisation solutions using cutting-edge methodology." — five vague superlatives, zero specific claims.'),
('Value Proposition', 'The hero section names who the offer is for', 5, 'The target audience is explicitly identified — by role, situation, or pain — within the hero section. Cialdini''s Unity: "for businesses running paid traffic" tells the right person "this is for me." PASS: "For marketing teams spending €3k+ per month on paid ads and wondering why the conversions don''t match." FAIL: "For businesses of all sizes looking to improve their online performance." — maximally vague.'),
('Value Proposition', 'Copy uses loss framing at least once in the hero', 5, 'At least one sentence in the hero frames around what the visitor is currently losing. Kahneman''s loss aversion: losses feel 2× more painful than equivalent gains. PASS: "Every month your page underperforms, you''re handing money to competitors who convert better." or "At 2% conversion rate, you''re losing €2,400/month that a 3% page would keep." FAIL: "Increase your conversion rate and unlock new revenue potential." — purely gain-framed, abstract.'),
('Value Proposition', 'The offer is concrete and specific, not categorical', 5, 'The offer names a specific deliverable with a specific scope — not a vague service category. Heath Brothers Concreteness: "70-criteria audit with revenue-leak calculation and 20-minute walkthrough, free" is sticky and memorable. "CRO services" is a category that disappears from memory. PASS: "A 70-point audit, a revenue-leak calculation showing €/month cost of each issue, and a 20-minute video walkthrough — delivered within 5 business days." FAIL: "Comprehensive conversion rate optimisation services tailored to your business needs."');

-- FW2: Relevance & Message Match (10 criteria)
INSERT INTO public.knowledge_base (category, criterion, weight, description) VALUES
('Relevance & Message Match', 'Page headline echoes the primary ad headline or keyword intent', 10, 'The ad and page headline share at least one key phrase or directly address the same intent. LIFT Relevance: the brain experiences a "scent" from ad to page. When the ad says "fix your landing page conversion rate" and the page headline says "We help businesses grow" — the scent breaks in the first 200–300ms. PASS: Ad: "Landing page audit — find out what''s killing your conversions" → Page: "Find out exactly what''s killing your conversions — in 20 minutes." FAIL: Ad: "CRO audit — see your revenue leak" → Page: "Welcome to Acme Agency. We build better digital experiences."'),
('Relevance & Message Match', 'Page addresses Schwartz Stage 3 (Solution Aware) — the default for paid search', 10, 'The page assumes the visitor knows the category exists and leads with differentiation, not category education. Someone clicking a Google Ad for "CRO agency" is Stage 3: they know what CRO is, they are evaluating providers. PASS: "Most CRO audits give you a list of recommendations. Ours gives you a revenue number attached to every single issue." FAIL: "What is conversion rate optimisation? CRO is the process of increasing the percentage of visitors who take a desired action..."'),
('Relevance & Message Match', 'Page serves a single, defined audience — not multiple segments', 10, 'The copy speaks to one visitor profile. No simultaneous targeting of e-commerce and SaaS, or startup and enterprise. PASS: Entire page written for "marketing managers at e-commerce brands spending €3k–€30k/month on paid ads." Every example uses product pages and cart abandonment. FAIL: "Whether you''re an e-commerce store, a SaaS startup, a service business, or an enterprise brand — we help all types of businesses."'),
('Relevance & Message Match', 'Page tone matches the sophistication level of the traffic source', 8, 'Copy complexity, vocabulary, and assumed knowledge level match what the visitor brings from the ad or referral source. PASS: LinkedIn ad targeting CMOs → page uses "conversion funnel architecture," "ROAS degradation," "attribution modelling." FAIL: Google Search Ad for "CRO agency" targeting CMOs → page opens with "Have you ever wondered why visitors leave your website without buying anything?"'),
('Relevance & Message Match', 'Offer on the page matches the offer in the ad exactly', 10, 'If the ad says "free audit," the page leads with a free audit. Bait-and-switch is the most common and most damaging relevance failure. PASS: Ad: "Free landing page audit" → Page hero: "Get your free landing page audit." FAIL: Ad: "Free CRO audit for your website" → Page: Primary CTA is "Book a £2,500 discovery workshop." Free audit mentioned in footnote.'),
('Relevance & Message Match', 'Page opens on the customer''s current reality, not the company''s aspirations', 8, 'The opening section mirrors the visitor''s current situation or frustration before introducing the solution. PASS: "Your ads are running. The budget is being spent. But the conversions aren''t coming in the way the numbers should allow." FAIL: "At Acme CRO, we''re passionate about conversion optimisation. Our team of experts has worked with over 200 clients."'),
('Relevance & Message Match', 'Industry or use-case specificity present if the ad targets a specific vertical', 5, 'If the traffic source targets a specific industry, the page contains at least one explicit reference to that context. PASS: E-commerce traffic → page mentions "product page conversion," "add-to-cart rate," "cart abandonment." FAIL: Ad targeting e-commerce managers → page talks only about "lead generation funnels" and "consultation bookings."'),
('Relevance & Message Match', 'No content contradicts or undermines the ad''s implicit promise', 8, 'The page contains no pricing, tone, or content signals that would surprise or alarm a visitor arriving from the specific ad. PASS: Ad targets SME budget → page shows pricing of €500–€2,000/month, uses accessible language. FAIL: Ad: "Affordable CRO for growing businesses" → Page shows "trusted by Nike, Amazon, HSBC" and minimum engagement of €50,000.'),
('Relevance & Message Match', 'Visual hierarchy reinforces the ad''s primary message', 5, 'The most prominent visual element relates directly to the ad''s main claim — not to brand aesthetics alone. PASS: Ad about "seeing what''s costing you conversions" → Hero shows an audit output screenshot with specific issues and revenue numbers. FAIL: Ad about analytical, data-driven auditing → Hero image is a soft-focus photo of two people shaking hands at a coffee shop.'),
('Relevance & Message Match', 'Page load speed: under 3 seconds on mobile (PageSpeed ≥ 70)', 10, 'First Contentful Paint under 3 seconds on simulated 4G. Google PageSpeed Insights mobile score ≥ 70. 53% of mobile visitors abandon a page taking longer than 3 seconds. PASS: PageSpeed mobile ≥ 70, FCP < 1.8s, LCP < 2.5s, CLS < 0.1, total page weight < 2MB. FAIL: 5MB hero image, 4 third-party tracking scripts synchronously, Google Fonts without preconnect.');

-- FW3: Clarity & Cognitive Ease (10 criteria)
INSERT INTO public.knowledge_base (category, criterion, weight, description) VALUES
('Clarity & Cognitive Ease', 'Primary CTA is visible without scrolling on both desktop and mobile', 10, 'A CTA button or form field is present above the fold — no scrolling required to find the first action opportunity. The above-fold CTA captures visitors who decide immediately (10–20%) and anchors the page''s purpose. PASS: URL input field + "Get my free audit" button visible on first load on iPhone 13 (390px viewport). FAIL: Hero section with 800px tall video background, CTA appears after 6 seconds below the video fold.'),
('Clarity & Cognitive Ease', 'One clearly dominant CTA — no two buttons of equal visual weight', 10, 'Only one button or action is visually dominant at any point. Secondary actions are visually subordinate. Hick''s Law: decision time increases logarithmically with the number of options. PASS: Primary: large cyan filled button "Get my free audit →" · Secondary: plain text link below in 70% opacity grey. FAIL: Two buttons side by side, identical size, identical cyan fill: "Get Free Audit" and "View Case Studies."'),
('Clarity & Cognitive Ease', 'No paragraph in body copy exceeds 3 sentences', 8, 'Every paragraph is readable in a single breath. Wall-of-text sections are absent. Krug: long paragraphs require active effort to parse — visitors skip them entirely. PASS: 3-sentence paragraph, each advancing the argument independently, readable in under 10 seconds. FAIL: A 7-sentence paragraph explaining full methodology, history of CRO, and delivery process as one unbroken block.'),
('Clarity & Cognitive Ease', 'No unexplained jargon or acronyms in above-fold copy', 8, 'Every word in the headline and first screen is understandable to a non-specialist in the target audience. Kahneman''s cognitive ease: things hard to parse feel less true and trustworthy. PASS: "We identify conversion leaks, calculate their monthly revenue cost, and give you a prioritised fix plan." FAIL: "Optimise your CVR using LIFT-model CRO methodology aligned with your ROAS targets and CAC/LTV ratio." — six acronyms for a general audience.'),
('Clarity & Cognitive Ease', 'Page has one primary goal — not multiple competing conversion objectives', 10, 'All roads lead to one action. Not simultaneously trying to generate leads, sell a product, build a newsletter, and book a call. PASS: Every CTA says "get the free audit." One destination, multiple paths to it. FAIL: "Book a consultation" + "Download our free guide" + "Follow us on LinkedIn" + "Subscribe to our newsletter" + "Shop our templates" — 5 different goals competing.'),
('Clarity & Cognitive Ease', 'Process explained in 3–4 steps maximum', 8, 'If the page includes a "how it works" section, it contains maximum 4 steps, with the first being minimal effort. StoryBrand: a plan with 3 steps removes decision paralysis. PASS: 1. Send us your URL (10 seconds) → 2. We audit across 70 criteria (48 hours) → 3. We walk you through findings on a free 20-minute call. FAIL: 8-step onboarding: Discovery call → Briefing document → Kick-off meeting → Audit phase 1 → Mid-point review → etc.'),
('Clarity & Cognitive Ease', 'Microcopy adjacent to the CTA explains what happens after clicking', 8, 'Within 1–2 lines of the CTA button, the visitor is told exactly what the next step is. Post-click anxiety is one of the highest-impact conversion killers. PASS: "Takes 60 seconds · No card required · We''ll email you the report" — answers three objections in 8 words. FAIL: Button: "Book a Call" — nothing else nearby. What kind of call? How long? Will it be a sales call?'),
('Clarity & Cognitive Ease', 'Visual hierarchy guides the eye in a clear top-to-bottom narrative path', 5, 'Page elements are sized and weighted so the reading order follows the persuasion sequence without visual confusion. Krug: users don''t read, they scan. PASS: H1 at 60px dominates, sub-headline at 20px clearly secondary, CTA in high-contrast accent colour. FAIL: 4 heading sizes all within 4px of each other, body copy and CTA same colours, all section headers identical.'),
('Clarity & Cognitive Ease', 'Body text is minimum 16px on mobile', 8, 'All paragraph copy renders at or above 16px on a standard mobile viewport (375px width). Text below 16px requires pinching. Google recommends 16px as mobile minimum. PASS: Body 16px base, section descriptions 17–18px, hero paragraph 18–20px. FAIL: Desktop CSS sets body at 16px but responsive breakpoint drops it to 13px; feature table uses 11px on mobile.'),
('Clarity & Cognitive Ease', 'Page section sequence follows narrative arc: Problem → Solution → Proof → CTA', 8, 'Sections appear in logical persuasion order. Each section earns the right for the next to exist. PASS: Hero (what + who + why now) → Problem (what''s breaking, what it costs) → Solution (how it works) → Proof (results) → CTA. FAIL: Hero → Client logos → Pricing → Problem section → CTA → Proof section after the CTA. Showing pricing before the problem produces sticker shock.');

-- FW4: Anxiety Reduction & Trust (10 criteria)
INSERT INTO public.knowledge_base (category, criterion, weight, description) VALUES
('Anxiety Reduction & Trust', 'At least one risk reversal is placed adjacent to the primary CTA', 10, 'Within 2 scroll-lengths of the primary CTA: a guarantee, free trial, "no card required," or equivalent. Kahneman loss aversion: the CTA asks the visitor to give something — the risk reversal removes the perceived loss. PASS: CTA button → "Free · No credit card · Findings are yours regardless" directly below. FAIL: Money-back guarantee mentioned in FAQ section at the bottom, 8 scrolls below the primary CTA.'),
('Anxiety Reduction & Trust', 'Social proof is specific, named, and verifiable — not anonymous', 10, 'Testimonials include at minimum a real name and a specific measurable result. Cialdini Social Proof hierarchy: named person + photo + company + specific result + timeframe = maximum credibility. PASS: "Conversion rate went from 1.4% to 3.8% in 6 weeks." — Jana Dvořák, Head of Marketing, Rohlik.cz [+ photo + LinkedIn link]. FAIL: "Absolutely transformed our conversion rate! These guys know what they''re doing." — J.D., Marketing Manager. Initials only, no number.'),
('Anxiety Reduction & Trust', 'The "will this work for me?" objection is explicitly addressed', 8, 'Copy somewhere on the page directly addresses whether the offer is relevant to the visitor''s specific situation. PASS: "This audit is most valuable if you''re spending at least €1,000/month on paid ads and have been running for more than 90 days." — clear fit criteria with honest disqualifier. FAIL: Page shows e-commerce case studies only, visitor is a SaaS founder, nowhere does it clarify applicability.'),
('Anxiety Reduction & Trust', 'The "is this a sales pitch?" fear is directly addressed', 8, 'For service pages with a call CTA: copy explicitly states what the call is NOT as well as what it IS. PASS: "The 20-minute call is a walkthrough of your audit findings — not a sales call. We don''t pitch anything. If you want to discuss working together, that''s a separate conversation you initiate." FAIL: CTA: "Book your free 30-minute strategy session." — no explanation of what happens; "strategy session" is universally understood as a sales call.'),
('Anxiety Reduction & Trust', 'Authority signals are specific and externally verifiable — not self-awarded', 8, 'Credibility indicators are independently checkable: named frameworks, specific methodologies, client logos, media mentions. PASS: "Our 70-criteria framework applies: LIFT Model (Chris Goward), Cialdini''s 7 Principles, Schwartz''s Buyer Awareness stages, Krug''s cognitive ease principles." — every framework can be Googled. FAIL: "Award-winning CRO agency · Industry-leading methodology · Best-in-class conversion specialists." — all unverifiable claims.'),
('Anxiety Reduction & Trust', 'Pricing is transparent, or the process to get pricing is clearly explained', 8, 'If pricing exists, it is shown. If pricing is custom, the exact process to get a quote is explained. Hidden pricing creates one of the strongest conversion anxieties. PASS: "Conversion Audit — €497. Includes: 70-criteria report, revenue-leak calculation, 20-min walkthrough. Payment after delivery." FAIL: "Pricing is bespoke to your needs. Contact us to discuss." — no indication of budget range.'),
('Anxiety Reduction & Trust', 'At least one piece of independently verifiable social proof exists', 10, 'There is at least one trust element that cannot have been fabricated: real named client, linked case study, third-party review count, media logo. PASS: Named client "Jana Dvořák, Head of Marketing, Rohlik.cz" — visitor can find her on LinkedIn. FAIL: Company-written case studies (no client named), anonymous testimonials, self-awarded "top agency" badge.'),
('Anxiety Reduction & Trust', 'A real human face is visible — founder, team, or actual person', 5, 'At least one authentic photograph of a real person associated with the business. Cialdini Liking: people buy from people. Stock photography registers as "no real humans here." PASS: Founder photo in about/proof section: real person, name, title, real environment. FAIL: Stock photo of smiling woman at a laptop for "team" section, no name, reverse image search finds it on 40 websites.'),
('Anxiety Reduction & Trust', 'Reciprocity principle applied — something of value given before anything is asked', 8, 'A free resource, tool, or audit is offered before committing. Cialdini Reciprocity: when you give first, the visitor feels a social obligation. Ariely: "FREE" triggers a disproportionate emotional response. PASS: "Free 70-criteria audit — we show you the full findings before you pay anything." FAIL: "Free consultation — 30 minutes with our team." — actually a discovery call where the company gathers info for a paid proposal.'),
('Anxiety Reduction & Trust', 'No fake urgency, fake countdown timers, or fabricated scarcity', 10, 'All urgency mechanisms are real and verifiable. No countdown timer resets on reload. Once a visitor identifies manufactured urgency, every other trust signal is viewed with the same suspicion. PASS: "Free founding client audits: 10 total (7 remaining as of March 2026). After the founding cohort is full, the audit moves to €497." FAIL: Countdown timer "OFFER ENDS IN 02:14:33" resets to 24 hours every page load; "Only 2 spots left" unchanged for 6 months.');

-- FW5: Distraction & Focus (10 criteria)
INSERT INTO public.knowledge_base (category, criterion, weight, description) VALUES
('Distraction & Focus', 'No standard navigation menu on the landing page', 10, 'The page has no full navigation bar with links to other website sections. Navigation links are exit paths. Removing navigation from dedicated landing pages increases conversion by 10–30%. PASS: Sticky header: Logo + "Get Free Audit" CTA button. Nothing else. FAIL: Sticky navigation: Home | About Us | Services | Case Studies | Blog | Pricing | Contact — 7 navigation links on a paid campaign page.'),
('Distraction & Focus', 'No social media icons linking off the page', 8, 'Social sharing buttons or profile links are absent, or if present are in the footer only and not prominently styled. Social media links are one-way exits. PASS: Social icons appear only in the footer, muted grey, small. FAIL: Four social media icons in the header next to the logo, styled in brand colours at 24px height.'),
('Distraction & Focus', 'No auto-playing video or audio on page load', 8, 'All media is paused by default. Nothing plays automatically. Auto-play violates the visitor''s expectation of control. PASS: Product demo video with large play button centred on thumbnail, auto-play off. FAIL: Full-screen background video in hero plays on load; separate testimonial video plays with audio when scrolled past.'),
('Distraction & Focus', 'No pop-up or interstitial appears in the first 30 seconds', 8, 'Any pop-up, chat widget expansion, or content-covering overlay does not appear within 30 seconds. The first 10–30 seconds are the most fragile moment. PASS: Chat widget collapsed by default, opens only on click; no pop-ups. FAIL: 3 seconds after load: full-screen pop-up "Sign up for our newsletter and get 10% off!" before the visitor has read the headline.'),
('Distraction & Focus', 'Form asks only for the minimum information required to deliver the offer', 8, 'Form contains only fields strictly necessary. No "company size," "phone number," or "how did you hear about us?" unless operationally required. HubSpot: reducing from 4 fields to 3 increases conversion by 50%. PASS: URL field + Email — two fields, both necessary. FAIL: URL · First name · Last name · Company · Size · Phone · Ad spend · "How did you hear about us?" · Job title — 9 fields.'),
('Distraction & Focus', 'All external links open in a new tab', 5, 'Any link that takes the visitor off the page opens target="_blank". An external link replacing the current tab closes the page permanently. PASS: Only external link is a client testimonial company name opening in new tab. FAIL: "Read our full methodology on our blog →" opens in same tab, navigating away.'),
('Distraction & Focus', 'Visual elements serve the conversion narrative — no decorative-only elements', 5, 'Each image, icon, or graphic either illustrates a claim, demonstrates the product, or builds trust. Pure decoration is absent. PASS: Hero: screenshot of actual audit report; proof section: before/after analytics graph. FAIL: Hero: abstract wavy gradient background; mid-page: isometric illustration of laptop with charts (generic).'),
('Distraction & Focus', 'Footer does not contain full site navigation or links to unrelated pages', 5, 'The footer is either minimal (privacy/terms only) or entirely absent. A comprehensive footer on a landing page is a navigation menu at the bottom of the funnel. PASS: Footer: Logo · One-line tagline · Privacy Policy (new tab) · Terms (new tab) · Copyright. FAIL: 4-column footer: Company · Services · Resources · Contact with 20+ links total.'),
('Distraction & Focus', 'A micro-commitment mechanism precedes the main CTA where possible', 5, 'Before or as part of the primary CTA, a small prior engagement (entering a URL, answering a question) commits the visitor before the full ask. Cialdini Commitment and Consistency: once a small action is taken, consistency compels completion. PASS: Step 1: Enter URL (10 seconds, non-personal). Step 2: A few details for revenue calculation. FAIL: Single-step form with Name, Company, Email, Phone, Message — full commitment up front.'),
('Distraction & Focus', 'Total page weight under 3MB (images + scripts + fonts)', 8, 'Total page resource weight under 3MB. Page weight causes layout instability and slow loading. PASS: Hero 180KB WebP, font subset 42KB, total JS 310KB deferred, total 1.4MB. FAIL: Hero 4.2MB JPEG, 6 Google Font families 1.2MB, Lottie animation 800KB, chat widget 650KB — total 7.8MB, 8–12 second load time.');

-- FW6: CTA Quality & Conversion Mechanics (10 criteria)
INSERT INTO public.knowledge_base (category, criterion, weight, description) VALUES
('CTA Quality & Conversion Mechanics', 'CTA button copy leads with the outcome the visitor wants — not the mechanism', 10, 'The button label names the result the visitor will get, not the action they take. JTBD: people don''t hire a CTA to "book a call" — they hire it to solve a problem. A/B tests show 15–40% lifts from outcome-first CTA copy. PASS: "See exactly what''s killing my conversions →" / "Get my free revenue leak report." FAIL: "Book a Call" / "Request an Audit" / "Contact Us" / "Schedule a Demo" / "Get Started" / "Submit."'),
('CTA Quality & Conversion Mechanics', 'CTA uses first-person language ("my", "I") not second-person ("your", "you")', 5, 'Button uses "Get my free audit" not "Get your free audit." Multiple controlled A/B tests show first-person outperforms by 5–20%. First-person puts the visitor into the action as agent. PASS: "Get my free audit →" / "Show me what I''m losing." FAIL: "Get your free audit →" / "Discover your conversion leaks." — grammatically correct but consistently lower-converting.'),
('CTA Quality & Conversion Mechanics', 'Primary CTA button is visually distinct — colour, size, and weight set it apart from all elements', 10, 'The CTA is immediately identifiable as the most important interactive element. Test: 2-second look → point to the most important element. If not the CTA, visual hierarchy failed. PASS: Dark page with grey/white typography. CTA: solid cyan, full width of form card, the only saturated colour on the page. FAIL: Blue page with blue sections and blue CTA slightly lighter blue — visually indistinct.'),
('CTA Quality & Conversion Mechanics', 'CTA is repeated after every major section — not only in the hero', 8, 'A CTA appears after the problem section, solution section, proof section, and final section. Visitors decide at different points. PASS: Hero: full CTA form. Problem section ends: small button. Proof section ends: full CTA repeated. Final: full CTA. FAIL: CTA form in hero only. Then: problem (no CTA) → services (no CTA) → proof (no CTA) → FAQ (no CTA) → footer (no CTA).'),
('CTA Quality & Conversion Mechanics', 'CTA includes three-layer structure: button → mechanism microcopy → risk reversal', 8, 'Adjacent to button: (1) outcome button copy, (2) mechanism/timeframe line, (3) risk reversal line. All three anxieties are active at the moment of decision. Combined lift typically 20–40% vs button alone. PASS: Button: "Get my free audit →" · "Takes 60 seconds · 20-min call walkthrough" · "Free forever · No credit card · Findings are yours." FAIL: Just the button: "Get Free Audit" — no microcopy, no risk reversal.'),
('CTA Quality & Conversion Mechanics', 'CTA touch target is minimum 44×44px on mobile', 8, 'Clickable area meets Apple/Google minimum recommended touch target size. Buttons smaller than this produce mis-clicks. PASS: Full-width on mobile, height 52px. Touch area: ~340×52px. FAIL: Desktop design shrunk on mobile: 180×32px. Text link CTAs at 12px height nearly impossible to tap with thumb.'),
('CTA Quality & Conversion Mechanics', 'The word "FREE" is used explicitly if the offer is free', 8, 'If the primary offer costs nothing, the CTA and adjacent copy uses the word "free." Ariely''s FREE! effect: "free" eliminates the cost-benefit calculation entirely. PASS: "Get my FREE conversion audit →" · "Free · No credit card." FAIL: "Get your complimentary conversion audit" / "No-cost page analysis" / "€0 audit report" — all lower-converting than "free."'),
('CTA Quality & Conversion Mechanics', 'The CTA section is the strongest-designed section — not the weakest', 5, 'The final CTA block receives equal or greater visual investment than the hero. Kahneman''s Peak-End Rule: ending is disproportionately influential. PASS: CTA section with same visual treatment as hero — gradient background, prominent typography, glow effects. FAIL: After elaborate page — plain white section with grey border form, small "Book a call" button.'),
('CTA Quality & Conversion Mechanics', 'CTA is a "variable reward" — the outcome is specific but the result is personal/unknown', 5, 'CTA creates curiosity about what the visitor will discover on their specific page. Eyal''s Hooked: variable reward activates dopaminergic reward system more than fixed reward. PASS: "Find out exactly what''s killing MY conversions →" — intriguing, personal, unknown specifics. FAIL: "Download the CRO audit checklist PDF" — completely predictable deliverable, no curiosity.'),
('CTA Quality & Conversion Mechanics', 'No generic CTA language: "Submit", "Click Here", "Learn More", "Contact Us" absent', 10, 'None of these four phrases appear as button labels. Bly''s CTA scoring: these score 1–2/10 — they communicate nothing about the outcome. PASS: "Submit" → "Get my free audit" · "Learn More" → "See how it works" · "Contact Us" → "Talk to us about your page." FAIL: Form button: "Submit" · Navigation: "Learn More" · Footer: "Contact Us" · Mid-page: "Click Here to Download."');

-- FW7: Urgency & Conversion Momentum (10 criteria)
INSERT INTO public.knowledge_base (category, criterion, weight, description) VALUES
('Urgency & Conversion Momentum', 'The cost of inaction is quantified somewhere on the page', 8, 'The page includes a specific calculation of what the visitor is currently losing per month. The most honest and compelling urgency mechanism. PASS: "At €5,000/month ad spend with a 1.8% CR, a 1-point improvement to 2.8% would generate approximately €2,800 more revenue per month — from the same budget." FAIL: "Every day your page underperforms is a missed opportunity for growth." — abstract, no number, no calculation.'),
('Urgency & Conversion Momentum', 'Real scarcity or capacity constraints stated if they genuinely exist', 5, 'If the service genuinely has limited capacity, this is stated clearly and specifically. Cialdini Scarcity: real constraints create urgency without damaging trust — but only when specific. PASS: "Free founding client audits: 10 total (7 remaining as of March 2026). After the founding cohort is closed, the audit moves to €497." FAIL: "Limited availability — book your spot now before it''s too late!" — displayed for months with no change, no number.'),
('Urgency & Conversion Momentum', 'Page narrative creates momentum — each section increases commitment, not resets it', 8, 'Sections are sequenced so each builds on the previous, moving the visitor progressively closer to conversion. Eyal''s Hooked model: each section should increase psychological investment. PASS: Hero → Problem agitation → Solution → Process → Proof → Founding offer. FAIL: Hero → Company history → Services list → Generic testimonials → CTA. Company history breaks momentum.'),
('Urgency & Conversion Momentum', 'Page names a shared enemy — a problem, practice, or situation both brand and visitor oppose', 5, 'Copy explicitly names what the brand is against. StoryBrand villain principle: shared enemy creates instant alignment, rapport, and differentiation simultaneously. PASS: "We''re against the agency playbook where the first thing that happens is a redesign proposal — before anyone has measured what''s actually wrong." FAIL: Page describes service and benefits with no mention of what approaches it considers inferior.'),
('Urgency & Conversion Momentum', 'Value is established before price is introduced', 8, 'If pricing exists, it appears only after value proposition, proof, and mechanism are fully established — never in the hero. Poundstone''s price-to-value sequencing: the longer a visitor reads before price, the less price-sensitive they become. PASS: Hero → Problem → Solution → Process → Proof → THEN: Pricing at €497. FAIL: Hero section: "CRO Audit — €1,200. Book now." — price before value.'),
('Urgency & Conversion Momentum', 'The "success state" is described concretely — the visitor can visualise the outcome', 8, 'The post-conversion outcome is described in specific, concrete terms. Heath Brothers Concreteness: the brain cannot form a desire for something it cannot visualise. PASS: "After the call, you''ll know: (1) the specific issues, (2) the monthly revenue estimate for each, (3) which 2–3 fixes have biggest impact, (4) whether your CR is above or below benchmark." FAIL: "After working with us, you''ll have a higher-converting page, better ROI, and clearer insight."'),
('Urgency & Conversion Momentum', 'An anchoring mechanism exists to make the offer''s value feel larger in context', 5, 'The page shows a reference price — cost of the problem, competitor pricing — before presenting the offer. Ariely''s anchoring: the first number becomes the mental reference point. PASS: "Agencies typically charge €5,000–€15,000 for a full rebuild. We audit it first for free — so any changes are backed by data." FAIL: "Get a free conversion audit." — stated in isolation, no anchor for "how valuable is this free thing?"'),
('Urgency & Conversion Momentum', 'A specific "reason to act today" exists beyond the general offer', 8, 'There is a specific, honest reason why acting today is better than next week. Return-and-convert rate below 3% without retargeting. PASS: "We''re accepting 7 more founding client audits (free). After the cohort closes, the audit is €497. At your estimated monthly leak of €2,400, every week you wait costs approximately €600." FAIL: Page describes offer clearly. No mention of why today is better than next month.'),
('Urgency & Conversion Momentum', 'Page tells a before/after story — current state vs transformed state', 5, 'The page shows where the visitor is now and where they''ll be after using the service. Heath Brothers'' Story principle: stories are 22× more memorable than facts. PASS: "Before: €6,000/month in ads, 1.4% CR, 84 leads/month. After audit and 3 fixes: 3.1% CR, 186 leads/month. Same budget. 12 weeks." FAIL: "Before: struggling with poor conversions. After: optimised pages, better results." — all abstract.'),
('Urgency & Conversion Momentum', 'The final section of the page is a CTA — not FAQ, blog links, or footer content', 8, 'The last substantial section before the footer is a CTA block. Kahneman''s Peak-End Rule: the ending is disproportionately influential. PASS: ... → FAQ → Final CTA section (full form, value proposition summary, founding offer, risk reversal) → Minimal footer. FAIL: ... → CTA section → "More resources" blog links → FAQ → About the team → Standard footer.');
